services:
  omnibus-server:
    image: ghcr.io/waterloo-rocketry/omnibus-server:main
    ports:
      - "5075:5075"
      - "5076:5076"
      - "5077:5077"

  omnibus-globallog:
    image: ghcr.io/waterloo-rocketry/omnibus-globallog:main
    depends_on:
      - omnibus-server
    environment:
      OMNIBUS_SERVER_HOST: omnibus-server

  omnibus-source-ljm:
    image: ghcr.io/waterloo-rocketry/omnibus-source-ljm:main
    depends_on:
      - omnibus-server
    environment:
      OMNIBUS_SERVER_HOST: omnibus-server
    volumes:
      - ./config:/config
