services:
  omnibus-server:
    image: ghcr.io/waterloo-rocketry/omnibus-server:main
    network_mode: host

  omnibus-globallog:
    image: ghcr.io/waterloo-rocketry/omnibus-globallog:main
    network_mode: host
    depends_on:
      - omnibus-server

  omnibus-source-ljm:
    image: ghcr.io/waterloo-rocketry/omnibus-source-ljm:main
    network_mode: host
    depends_on:
      - omnibus-server
    volumes:
      - ./config:/config
