[project]
name = "ljm-source"
version = "0.1.0"
description = "LabJack LJM DAQ Box Source"
requires-python = ">=3.11"
dependencies = ["omnibus", "labjack-ljm"]

[tool.uv.sources]
omnibus = {workspace = true}
