[project]
name = "omnibus-ws-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask-socketio>=5.5.1",
    "flask">=3.1.2,
    "eventlet">=0.40.4
]
