[project]
name = "globallog"
version = "0.1.0"
description = "Global Omnibus Logger"
requires-python = ">=3.11"
dependencies = [
    "msgpack>=1.1.1",
    "omnibus",
]

[tool.uv.sources]
omnibus = {workspace = true}
